version: "3"
services:
  app:
    build: .
    container_name: "timeoff_app"
    restart: always
    volumes:
      - ./app.json:/app/timeoff-management/config/app.json
      # - /timeoff-management/db/db.development.sqlite:/app/timeoff-management/db.development.sqlite  #launch First time without this!
    ports:
      - '3000:3000'